name: Musicien II Hizq
favicon: null
layout_spectrum: 0.4367622
typography_spectrum: 0.7311828
title: Musicien II Hizq
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#125688'
    - '#25272A'
    - '#A2B2B5'
    - '#FAD1BC'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
