title: Musicien II Hizq
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.25
  brandStrength: 0
  lightness: 0.5625
  brandColors:
    - '#FFFFFF'
    - '#125688'
    - '#25272A'
    - '#A2B2B5'
    - '#FAD1BC'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Musicien II Hizq
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7311828
layout_spectrum: 0.4367622
