analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6362007
  brandStrength: 1
  lightness: 0.4480287
  brandColors:
    - '#060606'
    - '#FFFFFF'
    - '#125687'
    - '#A5A6AA'
    - '#CE222F'
  rhythmicContrast: 0.4587814
typography_spectrum: 0.1249636693391949
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.4462366
favicon: null
name: Musicien II Hizq
