name: Auteur II Hizq
layout_spectrum: 0.4367622
typography_spectrum: 0.7311828
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#FFFFFF'
    - '#125688'
    - '#25272A'
    - '#A2B2B5'
    - '#FAD1BC'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose:
  - type: contact
    label: Mail Me
    url: 'mailto:musicienIIhizq@protonmail.ch'
  - type: contact
    label: Drop a Line
    url: 'tel:4435293963'
title: Verse
description: Instruments. Lyrics. Vocals.
author:
  name: HizqiyahY
  email: musicienhizq@protonmail.ch
content_rating:
  adult: false
content: []
github: true
